spring.datasource.url=${MYSQL_DATASOURCE_URL:jdbc:mysql://localhost:3306/coffee_project?serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
spring.datasource.username=${MYSQL_DATASOURCE_USERNAME:root}
spring.datasource.password=${MYSQL_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=${MYSQL_DDL_AUTO:update}
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
