spring.application.name=CoffeeProject

coffee.outbox.scheduler.enabled=false
coffee.outbox.scheduler.fixed-delay-ms=5000
coffee.outbox.scheduler.initial-delay-ms=5000
coffee.outbox.external-url=http://localhost:8081/mock-api/orders/completed
coffee.outbox.batch-size=10
coffee.outbox.max-retry-count=3
